[tox]
minversion = 4.0
envlist =
    py3{10,11,12}-dj42
    py3{10,11,12,13}-dj52
    py3{12,13}-dj60
    coverage

[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313

[testenv]
skipsdist = true
package = editable
basepython =
    py310: python3.10
    py311: python3.11
    py312: python3.12
    py313: python3.13
setenv =
    DJANGO_SETTINGS_MODULE = dbtemplates.test_settings
deps =
    coverage
    pytest
    pytest-django
    dj42: Django>=4.2,<4.3
    dj52: Django>=5.2,<5.3
    dj60: Django>=6.0,<6.1

commands =
    python --version
    python -c "import django ; print(django.VERSION)"
    coverage run --branch --parallel-mode -m pytest {posargs:dbtemplates}

[testenv:coverage]
basepython = python3.10
deps = coverage
commands =
    coverage combine
    coverage report
    coverage xml
